// prototype-nextjs/app/groups/[slug]/attck/page.tsx
import { getGroupContent, getGroupSlugs } from '@/lib/content'
import MarkdownRenderer from '@/components/MarkdownRenderer'
import Badge from '@/components/Badge'
import type { Metadata } from 'next'

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>
}): Promise<Metadata> {
  const { slug } = await params
  const { frontmatter } = getGroupContent(slug, undefined, 'attck')
  return { title: (frontmatter.title as string) || 'ATT&CK Matrix' }
}

export async function generateStaticParams() {
  return getGroupSlugs().map((slug) => ({ slug }))
}

export default async function AttckPage({
  params,
}: {
  params: Promise<{ slug: string }>
}) {
  const { slug } = await params
  const { frontmatter, content } = getGroupContent(slug, undefined, 'attck')

  const mitreId = frontmatter.mitre_group_id as string | undefined
  const mitreUrl = frontmatter.mitre_group_url as string | undefined

  return (
    <div>
      <div className="mb-6 flex flex-wrap items-start justify-between gap-3">
        <div>
          <h1 className="text-2xl font-bold text-[#e6edf3]">
            {(frontmatter.title as string) || 'ATT&CK Matrix'}
          </h1>
          {mitreId && (
            <p className="text-sm text-[#8b949e] mt-1">
              MITRE ATT&CK Group{' '}
              {mitreUrl ? (
                <a
                  href={mitreUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-[#58a6ff] hover:underline font-mono"
                >
                  {mitreId}
                </a>
              ) : (
                <span className="font-mono text-[#d29922]">{mitreId}</span>
              )}
            </p>
          )}
        </div>
        <Badge variant="warning">⚔️ ATT&CK Matrix</Badge>
      </div>
      <MarkdownRenderer content={content} />
    </div>
  )
}

// prototype-sveltekit/src/routes/groups/[slug]/attck/+page.svelte
<script lang="ts">
  import MarkdownRenderer from '$lib/components/MarkdownRenderer.svelte';
  import type { PageData } from './$types';
  let { data }: { data: PageData } = $props();

  const title = (data.frontmatter.title as string) || 'ATT&CK Matrix';
  const mitreId = data.frontmatter.mitre_group_id as string | undefined;
  const mitreUrl = data.frontmatter.mitre_group_url as string | undefined;
</script>

<svelte:head><title>{title} — APT Research Platform</title></svelte:head>

<div>
  <div class="mb-6 flex flex-wrap items-start justify-between gap-3">
    <div>
      <h1 class="text-2xl font-bold text-[#e6edf3]">{title}</h1>
      {#if mitreId}
        <p class="text-sm text-[#8b949e] mt-1">
          MITRE ATT&CK Group
          {#if mitreUrl}
            <a href={mitreUrl} target="_blank" rel="noopener noreferrer"
               class="text-[#58a6ff] hover:underline font-mono">{mitreId}</a>
          {:else}
            <span class="font-mono text-[#d29922]">{mitreId}</span>
          {/if}
        </p>
      {/if}
    </div>
    <span class="inline-flex items-center px-2.5 py-1 rounded-full text-xs font-medium
                 bg-[#161b22] text-[#d29922] border border-[#d29922]/30">
      ⚔️ ATT&CK Matrix
    </span>
  </div>
  <MarkdownRenderer content={data.content} />
</div>
